version: '3'
services: 
  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:300"
    depends_on:
      - database
    networks:
      - app-network


  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  networks:
    app-network:
      driver: bridge    
